spring:
  application:
    name: "configserver"

  profiles:
#    active: native
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/adityathodsare/configuration-for-microservises.git
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "classpath:/config"


encrypt:
  key: "adityaamolthodsare123098"

server:
  port: 8071