
#spring:
#  config:
#    activate:
#      on-profile: "prod"

build:
  version: "v1"

accounts:
  message: "welcome to accounts Microservice production apis "
  contactDetails:
    email: "shree@gmail.com"
    mobileNumber: "1234567890"
  callSupport:
    - "shree@gmail.com"
    - "1234567890"
